# Defaults here https://github.com/bbatsov/rubocop/blob/v0.37.2/config/default.yml

inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  Exclude:
    - "bin/bundle"
    - "bin/cucumber"
    - "bin/qgsocksify"
    - "bin/rails"
    - "bin/rake"
    - "bin/rspec"
    - "bin/rubocop"
    - "bin/setup"
    - "bin/spring"
    - "bin/update"
    - "bin/yarn"
    - "db/old_migrations/*"
    - "db/schema.rb"
    - "features/*"
    - "node_modules/**/*"
    - "vendor/**/*"
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

Layout/AlignHash:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/IndentFirstArgument:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/LambdaCall:
  Exclude:
    - '**/*.jbuilder'

Layout/DotPosition:
  EnforcedStyle: leading

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/BlockDelimiters:
  Description: Avoid using {...} for multi-line blocks (multiline chaining is always
    ugly). Prefer {...} over do...end for single-line blocks.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#single-line-blocks
  Enabled: false

Style/Lambda:
  Description: 'Use the new lambda literal syntax for single-line blocks.'
  Enabled: false

Style/MultilineBlockChain:
  Description: 'Avoid multi-line chains of blocks.'
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#single-line-blocks
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma

Style/Attr:
  Exclude:
    - app/graphql/**/*.rb
    - db/schema.rb

Metrics/BlockLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb
    - spec/support/shared_examples/**/*.rb

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional
  SupportedStylesForLeadingUnderscores:
    - disallowed
    - required
    - optional

Metrics/ClassLength:
  Exclude:
    - app/models/payment.rb
    - app/models/brand_payment.rb
    - app/models/subscription_item.rb
    - app/models/pitch.rb
    - app/models/frilans_finans_payments_file.rb
    - app/models/product.rb
    - app/models/outcome.rb
    - app/models/brand_xlsx_invoice.rb
    - app/models/ambassador.rb
    - app/models/offer_order.rb
    - app/models/blueprint.rb
    - app/models/payment_reward.rb
    - app/models/venue_invoice.rb
    - app/models/order.rb
    - app/models/offer.rb
    - app/models/venue.rb
    - app/models/subscription.rb
    - app/models/course.rb
    - app/models/checkin.rb
    - app/presenters/customer_invoice_presenter.rb
    - app/presenters/venue_invoice_presenter.rb
    - app/graphql/paginate_field.rb
    - app/controllers/app/v1/academy/products_controller.rb
    - app/controllers/app/v3/pipeline_results_controller.rb
    - app/controllers/app/v3/venues_controller.rb
    - app/controllers/apply_controller.rb
    - app/controllers/slack_controller.rb
    - app/services/create_fortnox_invoice.rb
    - app/services/mandrill/venue_invoice_to_mandrill_attributes.rb
    - app/services/mandrill/offer_order_to_mandrill_attributes.rb
    - app/services/import_venue.rb
    - app/services/create_customer_invoice.rb
    - app/services/form_builder/send_to_zapier.rb
    - app/services/form_builder/send_mandrill_email.rb
    - app/models/external/slack_bot.rb
    - app/models/pdf_generators/driver.rb
    - app/models/pdf_generators/templates/invoice/venue_invoice_base.rb
    - lib/generators/graphql_mutation/graphql_mutation_generator.rb
    - app/graphql/mutation_type.rb
    - app/graphql/query_type.rb
    - spec/support/graphql_matchers/**/*.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - app/models/subscription_item.rb
    - app/models/venue.rb
    - app/models/concerns/reward.rb
    - app/presenters/pitch_presenter.rb
    - app/serializers/app/v3/large/activities_serializer.rb
    - app/graphql/resolvers/create_comment_resolver.rb
    - app/controllers/app/v2/me_controller.rb
    - app/controllers/slack_controller.rb
    - app/services/import_venue.rb
    - app/services/save_forwarded_lead_assignment.rb
    - app/services/save_pitch.rb
    - app/models/routers/login.rb
    - app/models/keys_from_params.rb
    - app/models/external/slack_bot.rb
    - spec/support/utils/keen_helper.rb

Metrics/ParameterLists:
  Exclude:
    - app/mailers/purchases_mailer.rb
    - app/models/geocoder.rb
    - app/jobs/create_zendesk_ticket_job.rb
    - app/helpers/application_helper.rb
    - app/services/create_scheduled_event.rb
    - spec/requests/app/v3/survey_results_spec.rb
    - spec/requests/app/v3/pipeline_results_spec.rb
    - app/models/stripe_payment.rb
    - app/models/pdf_generators/components/heading_value_list.rb
    - app/models/pdf_generators/components/key_value_list.rb

Metrics/PerceivedComplexity:
  Exclude:
    - app/models/concerns/reward.rb
    - app/presenters/pitch_presenter.rb
    - app/graphql/resolvers/create_comment_resolver.rb
    - app/controllers/app/v2/me_controller.rb
    - app/services/import_venue.rb
    - app/services/save_forwarded_lead_assignment.rb
    - app/services/save_pitch.rb
    - app/models/routers/login.rb
    - app/models/keys_from_params.rb
    - spec/support/utils/keen_helper.rb

Naming/UncommunicativeMethodParamName:
  Exclude:
    - app/mailers/brand_specialist_notifications.rb
    - app/utils/date_params.rb
    - app/models/device.rb
    - app/graphql/resolvers/notifications.rb
    - app/graphql/resolvers/products.rb
    - app/graphql/resolvers/ambassador_tasks.rb
    - app/controllers/concerns/null_serializer_attributes_remover.rb
    - app/helpers/admin/admin_helper.rb
    - app/helpers/application_helper.rb
    - app/services/search_duplicate_venue.rb
    - app/models/venue_search/query_executor.rb
    - app/models/feature_flags/version.rb
    - app/models/pdf_generators/components/list.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Lint/InheritException:
  EnforcedStyle: standard_error

Style/GuardClause:
  Enabled: false

Capybara/FeatureMethods:
  Exclude:
    - 'spec/models/feature_flags/rules_spec.rb' # False positive

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - as
    - and

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*_spec.rb'
    - 'spec/lib/**/integration/**/*_spec.rb'

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/models/feature_flags/rules_spec.rb' # False positive

RSpec/ExampleLength:
  Enabled: false

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/PredicateMatcher:
  Enabled: false
