# Defaults here https://github.com/bbatsov/rubocop/blob/v0.37.2/config/default.yml

inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  Exclude:
    - "bin/console"
  TargetRubyVersion: 2.6

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/DotPosition:
  EnforcedStyle: leading

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/BlockDelimiters:
  Description: Avoid using {...} for multi-line blocks (multiline chaining is always
    ugly). Prefer {...} over do...end for single-line blocks.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#single-line-blocks
  Enabled: false

Style/Lambda:
  Description: 'Use the new lambda literal syntax for single-line blocks.'
  Enabled: false

Style/MultilineBlockChain:
  Description: 'Avoid multi-line chains of blocks.'
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#single-line-blocks
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma

Metrics/BlockLength:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb
    - spec/support/shared_examples/**/*.rb

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional
  SupportedStylesForLeadingUnderscores:
    - disallowed
    - required
    - optional

Metrics/ClassLength:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Lint/InheritException:
  EnforcedStyle: standard_error

Style/GuardClause:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - as
    - and

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Enabled: false

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/PredicateMatcher:
  Enabled: false

RSpec/EmptyLineAfterExample:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

RSpec/RepeatedExampleGroupDescription:
  Enabled: true

RSpec/RepeatedExampleGroupBody:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true
